import Head from "next/head";
import { useEffect, useRef, useState } from "react";
import useSWR from "swr";
import { Container, Row, Col, Button, InputGroup, Table } from "react-bootstrap";
import styles from "../styles/Home.module.css";
import PyboNavBar from "../components/pyboNavBar";
import Link from "next/link";
import { useRouter } from "next/router";

const fetcher = (...args) => fetch(...args).then((res) => res.json());

export default function Home() {
  // useRouter
  const router = useRouter();

  // pageIndex
  const storedPage = typeof window !== "undefined" && localStorage.getItem("pageIndex");
  const [pageIndex, setPageIndex] = useState(storedPage || 1);

  // search
  const storedSearch = typeof window !== "undefined" && localStorage.getItem("searchKeyword");
  const [kw, setKw] = useState(storedSearch || "");

  // focus DOM
  const searchRef = useRef();

  // fetch the data
  const { data, error } = useSWR(
    `http://127.0.0.1:5000/question/list?page=${pageIndex}&kw=${kw}`,
    fetcher,
    { keepPreviousData: true },
  );

  // set page change
  const handlePageChange = (pageIndex) => {
    router.push({ query: { page: pageIndex, kw: kw } });
    setPageIndex(pageIndex);
    localStorage.setItem("pageIndex", pageIndex);
  };

  // set search change
  const handleSearchChange = () => {
    const searchKeyword = searchRef.current.value;
    router.push({ query: { kw: searchKeyword } });
    setKw(searchKeyword || "");
    localStorage.setItem("searchKeyword", searchKeyword);
  };

  // useEffect
  useEffect(() => {
    setKw(router.query.kw || "");
    searchRef.current && (searchRef.current.value = router.query.kw || "");
    setPageIndex(router.query.page);
  }, [router.query.page, router.query.kw]);

  if (error) return <div>Failed to load</div>;
  if (!data) return <div>Loading...</div>;

  return (
    <>
      <Head>
        <title>udacity Pybo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <PyboNavBar />
        <Container className="my-3">
          <Row className="my-3">
            <Col className="col-6">
              <Button variant="primary" href="#">
                Write the Question
              </Button>
            </Col>
            <div className="col-6">
              <InputGroup>
                <input type="text" className="form-control" ref={searchRef} />
                <div className="input-group-append">
                  <Button variant="outline-secondary" onClick={handleSearchChange}>
                   Search
                  </Button>
                </div>
              </InputGroup>
            </div>
          </Row>
          <Table>
            <thead>
              <tr className="text-center table-dark">
                <th>No.</th>
                <th style={{ width: "50%" }}>Subject</th>
                <th>Writer</th>
                <th>Date</th>
              </tr>
            </thead>
            <tbody>
              {data.questions.map(function (question, i) {
                return (
                  <tr className="text-center" key={question.id}>
                    <td>{data.total - (data.page - 1) * data.per_page - i}</td>
                    <td className="text-start">
                      <Link href={`question/pyboQuestionDetail/?question_id=${question.id}`}>
                        {question.subject}
                      </Link>
                      {question.answer_set && question.answer_set.length > 0 && (
                        <span className="text-danger small mx-2">
                          {question.answer_set.length}
                        </span>
                      )}
                    </td>
                    <td>{question.user.username}</td>
                    <td>{new Date(question.create_date).toLocaleDateString()}</td>
                  </tr>
                );
              })}
            </tbody>
          </Table>

          <ul className="pagination justify-content-center">
            {data.has_prev ? (
              <li className="page-item">
                <a
                  className="page-link"
                  data-page={data.prev_num}
                  onClick={() => handlePageChange(pageIndex - 1)}
                >
                  Prev
                </a>
              </li>
            ) : (
              <li className="page-item disabled">
                <a className="page-link" tabIndex="-1" aria-disabled="true">
                  Prev
                </a>
              </li>
            )}
            {data.page_nums.map(function (page_num, i) {
              if (page_num) {
                if (page_num != data.page) {
                  return (
                    <li className="page-item" key={page_num}>
                      <a
                        className="page-link"
                        data-page={page_num}
                        onClick={() => handlePageChange(page_num)}
                      >
                        {page_num}
                      </a>
                    </li>
                  );
                } else {
                  return (
                    <li className="page-item active" aria-current="page" key={page_num}>
                      <a className="page-link">{page_num}</a>
                    </li>
                  );
                }
              } else {
                return (
                  <li className="disabled" key={page_num || i + "1"}>
                    <a className="page-link">...</a>
                  </li>
                );
              }
            })}
            {data.has_next ? (
              <li className="page-item">
                <a
                  className="page-link"
                  data-page={data.next_num}
                  onClick={() => handlePageChange(pageIndex + 1)}
                >
                  Next
                </a>
              </li>
            ) : (
              <li className="page-item disabled">
                <a className="page-link" tabIndex="-1" aria-disabled="true">
                  Next
                </a>
              </li>
            )}
          </ul>
        </Container>
      </main>
    </>
  );
}
