import QuestionForm from "@/components/questionForm";
import { getCsrfToken, useAuthContext } from "@/contexts/context";
import Head from "next/head";
import { useRouter } from "next/router";
import { useRef } from "react";
import useSWRMutation from "swr/mutation";

export default function Create() {
  //auth
  const { user, accessToken } = useAuthContext();

  // router
  const router = useRouter();

  // ref
  const formRef = useRef();

  // remote mutate
  const { data: question, trigger: createQuestion } = useSWRMutation(
    `${process.env.API_URL}/question/create/`,
    async (url, { arg }) => {
      const question = await fetch(url, {
        method: "POST",
        headers: {
          // pybo server가 html/api 방식을 공유하기 때문에 form으로 전송
          "Content-Type": "application/x-www-form-urlencoded",
          Authorization: `Bearer ${accessToken}`,
        },
        credentials: "include",
        body: arg,
      })
        .then((res) => res.json())
        .then((data) => data);

      if (question.errors) {
        return question;
      }

      // redirect to list
      router.push("/");
    },
  );

  // create question
  const handleCreateQuestion = async (e) => {
    e.preventDefault();

    const formDate = new FormData(formRef.current);
    // csrftoken을 form feild로 전송
    formDate.append("csrf_token", await getCsrfToken());
    createQuestion(new URLSearchParams(formDate));
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <QuestionForm
          question={question}
          errors={question && question.errors}
          formRef={formRef}
          onClick={handleCreateQuestion}
        />
      </main>
    </>
  );
}
