import QuestionForm from "@/components/questionForm";
import { useAuthToken } from "@/contexts/context";
import Head from "next/head";
import { useRouter } from "next/router";
import { useRef } from "react";
import useSWRMutation from "swr/mutation";

export default function Create() {
  //auth
  const accessToken = useAuthToken();

  // router
  const router = useRouter();

  // ref
  const formRef = useRef();

  // remote mutate
  const { data: question, trigger: createQuestion } = useSWRMutation(
    `${process.env.API_URL}/question/`,
    async (url, { arg }) => {
      const question = await fetch(url, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${accessToken}`,
        },
        body: arg,
      })
        .then((res) => res.json())
        .then((data) => data);

      if (question.errors) {
        return question;
      }

      // redirect to list
      router.push("/");
    },
  );

  // create question
  const handleCreateQuestion = async (e) => {
    e.preventDefault();

    const formDate = new FormData(formRef.current);
    createQuestion(JSON.stringify({
      subject: formDate.get("subject"),
      content: formDate.get("content"),
    }));
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <QuestionForm
          question={question}
          errors={question && question.errors}
          formRef={formRef}
          onClick={handleCreateQuestion}
        />
      </main>
    </>
  );
}
