import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useRef } from "react";
import useSWRMutation from "swr/mutation";
import { getCsrfToken, useAuthContext } from "@/contexts/context";
import QuestionForm from "@/components/questionForm";

export default function Modify() {
  // auth
  const { accessToken } = useAuthContext();

  // router
  const router = useRouter();

  // ref
  const formRef = useRef();

  // remote mutate
  const {
    data: question,
    trigger: modifyQuestion,
    error,
  } = useSWRMutation(
    `${process.env.API_URL}/question/${router.query.id}`,
    async (url, { arg }) => {
      const question = await fetch(url, {
        method: arg ? "PUT" : "GET",
        headers: {
          // pybo server가 html/api 방식을 공유하기 때문에 form으로 전송
          "Content-Type": "application/x-www-form-urlencoded",
          Authorization: `Bearer ${accessToken}`,
        },
        credentials: "include",
        body: arg,
      })
        .then((res) => res.json())
        .then((data) => data);

      if (!arg || question.errors) {
        return question;
      }

      // redirect
      router.push(`/question?id=${router.query.id}`);
    },
  );

  // fetch question
  useEffect(() => {
    if (accessToken) modifyQuestion();
  }, [accessToken]);

  // modify question
  const handleModifyQuestion = async (e) => {
    e.preventDefault();

    const formDate = new FormData(formRef.current);
    // csrftoken을 form fieldf 전송
    formDate.append("csrf_token", await getCsrfToken());
    modifyQuestion(new URLSearchParams(formDate));
  };

  if (error) return <div>Failed to load</div>;
  if (!question) return <div></div>;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <QuestionForm
          question={question}
          errors={question && question.errors}
          formRef={formRef}
          onClick={handleModifyQuestion}
        />
      </main>
    </>
  );
}
